site_name: Data Analysis
site_description: A netcore microservices chassis
site_author: Gonzalo Herrera 
site_url: https://data-office.github.io/docs/

theme:
  name: material
  language: en
  features:
    - tabs
  palette:
    primary: black
  font:
    text: Roboto
    code: Roboto Mono
  logo: 'images/A-andreani.png'

markdown_extensions:
  - markdown.extensions.admonition
  - markdown.extensions.codehilite:
      guess_lang: false
  - markdown.extensions.toc:
      permalink: true
  - pymdownx.superfences
  - pymdownx.tabbed

nav:
  - Overview: index.md
  - Aquitectura : arquitectura.md
  - Azure Databricks:
    - Overview: overview_databricks.md
    - Conceptos: concepts_databricks.md
    - Databricks Data Sciente & Engineering: databricks_datascience&engineering.md
    - Databricks Machine Learning: databricks_machinelearning.md
    - Databricks SQL: databricks_sql.md
    - Databricks integrations: databricks_integrations.md
    - Data Engineering: Data_engineering.md
  - Gobierno del Dato:
    - Overview : overview_gobierno_del_dato.md
    - Purview: purview.md
  - DevOps:
    - Overview : EN_CONSTRUCCIÓN.md
    - DevOps: EN_CONSTRUCCIÓN.md
  - Airflow:
    - Overview : overview_airflow.md
    - DAG : dag.md
    - Casos de uso : casos_uso.md
    - Aquitectura : airflow.md
  - Deequ:
    - Overview : overview_deequ.md
  - Sonarqube:
    - Overview : overview_Sonarqube.md
    - SonarQube : sonarqube.md
  - Glosario de Términos: glosario_de_terminos.md
  - Links de interes: link_interes.md
  
    
  ##- Version 2.1:    
  ##  - Overview: 2.1/index.md
    
  
